### ISSUE TITLE
Vim or nano?

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#10]
Currently, we install only `vim` in all base images. I'm perfectly fine with vim, but I'm not sure if most ML researchers are.

Maybe we should ask our users during cookiecutting? :smile: 

```
full_name [Your name]: 
email [Your email address (e.g. you@example.com)]: 
project_name [Name of the project]: 
project_slug [name-of-the-project]: 
project_short_description [A short description of the project]: 
code_directory [modules]: 
vim_or_nano [vim]:
...
```

**Comment by YevheniiSemendiak** [comment]
both are there, no need to overcomplicate such things, imo
