### ISSUE TITLE
Speedup apt-get update/install

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#11]
Purpose: minimize time of `make setup`.

Possible solutions:
1. optimize `apt-get update`: use the closest apt mirror (use automatic tools like [`netselect-apt`](https://www.unixmen.com/find-fastest-mirror-debian-derivatives/))
2. optimize `apt-get install`: [`apt-fast`](https://vitux.com/how-to-speed-up-package-downloads-and-updates-with-apt-fast-on-ubuntu/) instead of `apt-get`

**Comment by YevheniiSemendiak** [comment]
not actual
