### ISSUE TITLE
Make tests on scikit-learn pass

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#26]
In https://github.com/neuromation/template-base-image/pull/20, we introduced tests for the base image, among which some tests on scikit-learn don't work:
- `pytest --verbose --pyargs sklearn`,
- `pytest --verbose --pyargs sklearn -k 'not test_estimate_bandwidth_1sample'`

(see these and other ignored tests in `./testing/recipes-ignore/`)

**Comment by YevheniiSemendiak** [comment]
not actual
