### ISSUE TITLE
[Maybe] Run some tests on the platform so that tests on GPU work

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#27]
See issue https://github.com/neuromation/template-base-image/issues/25 (closed): the tests work on a GPU job, but currently we run all tests in a bare docker container without GPU, so tests `python -c 'import tensorflow as tf; assert tf.test.is_gpu_available()` and `python -c 'import torch; assert torch.cuda.is_available()'` fail.

**Comment by YevheniiSemendiak** [comment]
not actual
