### ISSUE TITLE
Store pip list output in CI artifacts (or github repo)

### ISSUE THREAD

**Issue by anayden** [neuro-inc/neuro-base-environment#29]
When we build a new version of base image we should do the following:
```
pip list | sort > pip_list.txt
```

Then this file (`pip_list.txt`) should be stored in CI artifacts.

Eventually we might want to store it in a separate github repo (e.g. `neuromation/template-base-image-packages`) where we would commit it via GitHub API ([docs](https://developer.github.com/v3/git/commits/#create-a-commit)). Having this history on GitHub gives us diff functionality out of the box.

**Comment by YevheniiSemendiak** [comment]
not actual, python versions are fixed in the requirements file
