### ISSUE TITLE
Set up versioning between Base image and Template

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#30]
Problem: https://neuromation.slack.com/archives/C9Z1UBC6A/p1571935404029900

we need to:
1. In Template, use exact version of the base image (`neuromation/base:v1.10`)
2. Push base image with a tag (currently, it only overrides `latest` on DockerHub)
3. Use same versions for Base image and Template

**Comment by YevheniiSemendiak** [comment]
not actual
