### ISSUE TITLE
Minor: Add original deepo Dockerfile to be able to use diff

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#34]
In order to be able to answer the question: "How did you derive your Dockerfile?", we need to show people a diff between our Dockerfile and deepo's Dockerfile.

1. Add `make` targets to re-generate Dockerfile
2. Add `make` targets to do diff

**Comment by YevheniiSemendiak** [comment]
not sure whether we need to answer that question, lets get back here if we do
