### ISSUE TITLE
Add git-lfs

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-base-environment#415]
As [requested](https://neuromation.slack.com/archives/C019S1X1WBG/p1650386101776889) by the Synthesis team.

**Comment by vsevolod-oparin** [comment]
Version must be >= 2.10. Version 2.9 has a bug.

**Comment by YevheniiSemendiak** [comment]
added in https://github.com/neuro-inc/neuro-base-environment/pull/422
