### ISSUE TITLE
Get rid of job timeout workaround

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#45]
Once quota enforcing is implemented server-side, we need to get rid of the workaround https://github.com/neuromation/template-base-image/pull/19

Solving this issue will also close https://github.com/neuromation/template-base-image/issues/44

**Comment by ayushkovskiy** [comment]
see proper implementation: https://github.com/neuromation/platform-api/pull/1044/

**Comment by YevheniiSemendiak** [comment]
not actual
