### ISSUE TITLE
Packages versioning problem

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#49]
Problem: many of our users (I asked @atselousov and @AlekseySh when they were working on their AI Kits) require pytorch and other libraries to have fixed versions -- they fix it in requirements.txt. As a result, base image grows to huge sizes (for example, @atselousov 's image was 10G).

We need to think what we can do:
1. Maintain multiple base images with the most significant versions of the packages. We could split image into layers in order to optimize the size of images cached on nodes (see https://github.com/neuromation/template-base-image/issues/46).
1.1 Pro: it solves the problem of long `make setup` and big image
1.2 Cons: Hard to maintain. Still a lots of images => space problem remains
2. Deal with it as it is (single docker image without versions fixed anywhere -- if a user specifies a version in `requirements.txt` and the it doesn't match what's installed, the image grows in size)
3. Fix versions in Dockerfile itself (https://github.com/neuromation/template-base-image/issues/29#issuecomment-559100131)

In any case, considering sizes of images (Gigabytes), we might need to implement [image deletion](https://github.com/neuromation/platform-registry-api/issues/44) very soon.

**Comment by YevheniiSemendiak** [comment]
image deletion is done
package versions are fixed and controlled via dependabot
of someone needs outdated version - he should use base image as base for is docker image and reinstall needed package
