### ISSUE TITLE
Support `opencv`: add explicit installation + tests

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/neuro-base-environment#50]
Deepo generator supports this option.

OpenCV is often used by ML engineers working with CV. It requires a bunch of systems libraries to be installed as well as python packages.

**Comment by ayushkovskiy** [comment]
requirements added: https://github.com/neuromation/neuro-base-environment/blob/5fd29712980a354049ea556e080631c7f0bfe491/targets/python36-jupyter-pytorch-tensorflow-jupyterlab/Dockerfile#L193

Also, need to add tests
