### ISSUE TITLE
Push base image to neuro registries as well

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#6]
Ultimate goal: speed up command `make save`.

Related issue: https://github.com/neuromation/platform-infra/issues/155. This will speed up running jobs from base image not only via `make setup`, but also via `make jupyter` etc. since user's image uses layers of the base image that are already cached on nodes.

In order to improve `neuro-save` stage of `make setup` (which pushes the newly created image to neuro-registry), we need to pre-load layers of the base image to neuro-registry as well. Should be done as a final step of base image's CI.

For now, it can be only `dev` and `staging`, but in future we better ask `platform-config` for URIs of image registries in all existing clusters and push our image there (using a specific super-token, probably).

**Comment by YevheniiSemendiak** [comment]
not actual
