### ISSUE TITLE
Prefix our custom env vars with `NM_`

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-base-environment#63]
so that our image+template don't fail one day when another application accidentally sets up env var that we use.

Examples:
- `EXPOSE_SSH` -> `NM_EXPOSE_SSH`
- `GCP_SERVICE_ACCOUNT_KEY_PATH` -> `NM_GCP_SA_KEY_PATH` (also shorten)
- `JOB_TIMEOUT` -> `NM_JOB_TIMEOUT` (note: we'll get rid of it in future)

**Comment by YevheniiSemendiak** [comment]
currently, we have only a single env var, which is propagated over other templates, lets' keep it as is with the possibility to reconsider it later
